#1 constuctor 2D Array
JaysGitLab/cs5666-spr17-javatrix-c2m2 pull request #58
Opened 2017-02-10 17:42 UTC by KaraBeason

Closes #1.  Added constructor that copies 2D array into matrix.  Unit tests pass, style check passes.  Admittedly I forgot to write the test first, but I will remember to do that from here on out!

2017-02-10 19:26 UTC, haietza requested changes
This constructor needs to throw an IllegalArgumentException. Add test for exception being thrown as well. I would also use m and n variables in test for consistency. Everything else looks good!

2017-02-10 19:37 UTC, KaraBeason commented
@haietza can you give me more information on the case in which it would throw this exception?

2017-02-10 19:48 UTC, KaraBeason commented
@haietza for the test, can you specify which line you're talking about?  Line 35 or the for loop?

2017-02-10 19:54 UTC, haietza commented
I initialized them at the start of my test and then used them in the array
initialization and in the for loop. Not major, just a suggestion to keep
our code consistent?

Michelle Melton
Web Developer/Programmer
Center for Academic Excellence

On Fri, Feb 10, 2017 at 2:48 PM, KaraBeason <notifications@github.com>
wrote:

> @haietza <https://github.com/haietza> for the test, can you specify which
> line you're talking about? Line 35 or the for loop?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JaysGitLab/cs5666-spr17-javatrix-c2m2/pull/58#issuecomment-279048067>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAo34r6otS3E2Mbmx0FEhHX8-kgK35nnks5rbL8fgaJpZM4L9p4h>
> .
>

2017-02-10 20:12 UTC, KaraBeason commented
@haietza Sorry, realized what you meant as soon as I commented about the variables (Seems to be a trend with me today - stupid brain!).  Yes, that makes sense to me!  Thank you!  Everything should be resolved now, I think.  LMK what you think!

2017-02-10 20:28 UTC, haietza commented
No worries - I have been doing that just about every time I commit and push
- I think of like 6 things I forgot! TGIF :).

Michelle Melton
Web Developer/Programmer
Center for Academic Excellence

On Fri, Feb 10, 2017 at 3:12 PM, KaraBeason <notifications@github.com>
wrote:

> @haietza <https://github.com/haietza> Sorry, realized what you meant as
> soon as I commented about the variables (Seems to be a trend with me today
> - stupid brain!). Yes, that makes sense to me! Thank you! Everything should
> be resolved now, I think. LMK what you think!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JaysGitLab/cs5666-spr17-javatrix-c2m2/pull/58#issuecomment-279053911>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAo34kDPd9g4kZNKMPQPDGZe3TvR8CY7ks5rbMS5gaJpZM4L9p4h>
> .
>

2017-02-10 20:29 UTC, haietza requested changes
Let me know what you think about these things...thanks!

2017-02-10 20:29 UTC, haietza commented on Javatrix.java
> +     **/
Doesn't this need an @throws tag?

2017-02-10 20:29 UTC, haietza commented on Javatrix.java
> +    public Javatrix(double[][] arr)
Doesn't this need a "throws IllegalArgumentException"?

2017-02-10 20:29 UTC, haietza commented on Javatrix.java
> +
Delete extra line?

2017-02-10 20:29 UTC, haietza commented on JavatrixTest.java
> +
Delete extra line?

2017-02-10 20:29 UTC, haietza commented on JavatrixTest.java
> +
Delete extra line?

2017-02-10 20:29 UTC, haietza commented on JavatrixTest.java
> +
Delete extra line?

2017-02-10 20:31 UTC, haietza commented
@caldwellc1 @KaraBeason Question - I had not been including the .class files in my commits because I think I remember Dr Fenwick not doing that in our previous assignment. Do either of you know what standard protocol is on this?

2017-02-10 20:48 UTC, haietza commented
@caldwellc1 @KaraBeason I have been using the method headers from the API, matching their naming convention for parameters, etc. Should we try to make all our code consistent in this way?

2017-02-11 21:59 UTC, KaraBeason commented
@haietza I think that's a good idea.  I don't see method headers in the API .... could you link me please?

2017-02-12 13:24 UTC, haietza commented
I was just using the headers in the API Dr Fenwick provided: http://cs.appstate.edu/~jbf/classes/cs5666/Javatrix/. But I just discovered that some of those won't pass checkstyle (using A for a parameter name), so I think as long as we are consistent between the team, we should be good :).

2017-02-12 13:24 UTC, haietza approved these changes
Looks good! Thanks!

2017-02-13 01:27 UTC, merged