#2 constructor2 d dimensions explicit
JaysGitLab/cs5666-spr17-javatrix-c2m2 pull request #59
Opened 2017-02-10 20:15 UTC by KaraBeason

Closes #2.  Add constructor that creates m by n matrix from a 2D array, taking the array, m and n as arguments. Tests pass, check style passes.

2017-02-10 20:43 UTC, haietza requested changes

2017-02-10 20:43 UTC, haietza commented on Javatrix.java
> +                if (i < m && j < n)
The API suggests that arguments don't need to be checked. Do you think the loop should just test i < m and j < n and only copy those specified rows/cols from the provided array, versus attempting to copy the whole thing and having to test the arguments?

2017-02-11 22:32 UTC, KaraBeason commented on Javatrix.java
> +                if (i < m && j < n)
In that case, is it the expected behavior that it throws an ArrayIndexOutOfBoundsException when given x and y greater than the dimensions of the array?  If so should I re-write my test for that case to expect an exception, or should I remove it?

2017-02-12 13:21 UTC, haietza commented on Javatrix.java
> +                if (i < m && j < n)
I think what you have looks right - we check the row length during each iteration and if it doesn't equal the initial n, then we know they are all not the same length and can throw the exception.

2017-02-12 13:44 UTC, haietza commented on Javatrix.java
> +                if (i < m && j < n)
Well, the API does not mention any exceptions, so I think the most efficient way to do it is how you have it implemented. Sorry - I was thinking about the case when m and n were less than the array's rows and columns, not when they were greater. I think the Javatrix class is good - let me review the tests below.

2017-02-12 13:44 UTC, haietza commented on JavatrixTest.java
> +            for (int j = 4; j < n; j++)
Why is j starting at 4 here?

2017-02-13 01:29 UTC, KaraBeason commented on JavatrixTest.java
> +            for (int j = 4; j < n; j++)
That is most definitely a typo.  Thanks for catching :)

2017-02-13 01:35 UTC, KaraBeason commented on Javatrix.java
> +                if (i < m && j < n)
Ah, gotcha!  I see you what you mean.  Ok I will leave as is for now!   Thanks!

2017-02-13 15:27 UTC, KaraBeason commented
@haietza is this good to be merged, or are changes still needed?  Thank you!

2017-02-13 15:57 UTC, haietza approved these changes
Sorry for the delay - looks good! Thanks!

2017-02-13 23:31 UTC, merged

2017-02-17 15:20 UTC, haietza commented
@KaraBeason Do you think we should change this to not check the arguments, as Dr Fenwick discussed in class today?

2017-02-17 17:27 UTC, KaraBeason commented
@haietza yes, I will push a fix up